### ISSUE TITLE
Good job !

### ISSUE THREAD

**Issue by youprint** [sleepybishop/artix_hostmot2#1]
I was about to do the same on an artix 7 and I was looking for a starting point when i saw this repo. I just want to know which artix 7 package are you using and which dev board are you using for testing.
i found a cheap simple dev board from OMDAZZ : https://fr.aliexpress.com/store/product/Xilinx-FPGA-Artix7-Artix-7-Development-Board-XC7A35T-Core-Board-with-SDRAM/2274002_32799960711.html?spm=a2g0w.12010612.8148356.6.683c7fa5Nbtv5g
it's a 256 package for 40$ but there is sdram which use some I/O.
If this firmware port is a success i'm planning to create my own board, more powerful than Mesa boards.

**Comment by sleepybishop** [comment]
the package should be the same (xc7a35tftg256-1), im using the au board from alchitry, (formerly embedded micro), despite sdram the fpga still offers plenty of io, i've provisioned 96 pins for hostmot2 use.

im still in testing phase, but the one thing i've yet to finish is the integration of the xadc for analog readings.

**Comment by youprint** [comment]
So you have sdram too on your board. The pb with FPGA dev board is that they are designed for video/analog so sdram will help. i will try to order this dev board to try your code.
